#!/bin/sh

case "${1}" in
        start)
                httpd
                ;;

        stop)
                pkill httpd
                ;;

        status)
                pidof httpd
                ;;

        *)
                exit 1
                ;;
esac
